### PR TITLE
fixes aidanholm/luakit#359

### PR DESCRIPTION
**Pull request by groolot**

### CODE REVIEW

**Comment by groolot** [comment]
As you want @aidanholm , but people may have scripted some stuff that will be broken if you totally remove it.

I suggest you to keep it as I requested.

**Comment by groolot** [comment]
You can also let people continue using their scripts with the `default` target rule that is an alias to `all`.

**Comment by aidanholm** [comment]
That is a good point. The entire point of the `default` target, however, was that it was the default. So 1) it'd be strange if scripts specified it explicitely (`make default`), and 2) with your suggested changes what the new default target (`all`) builds is _different_ to what the `default` target builds.

I think a good solution would be to revert ece8969 as I suggested, and then add `default` as an alias to `all` that prints a deprecation warning. Thoughts?

**Comment by groolot** [comment]
I think this is the best way. Do you want me to PR that ?

**Pull request closed without merging**
